server:
  port: 9903
  
app:
  datasource:
    driver: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = localhost)(PORT = 1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = orcl.168.1.108)))
    username: test
    password: 123456
    initialSize: 30
    maxActive: 30
    maxIdle: 30
    minIdle: 30
    maxWait: 30